### ISSUE TITLE
Get 2 months of avalible periods performance issue

### ISSUE THREAD

**Issue by ericeric284** [EasyAbp/BookingService#20]
In our team's use case, we want to display 2 months of calendar with avalible periods.
For each day , it will shows "avalible" if there are any periods avalible that day, otherwise the day will show "unavalible".

We implement the api like the following example, but this is not very performant due to the loop count (costs around 20 sec for two months of days * 20 asset), perhaps a cache is needed , or use a different api to improve performance since we don't actually need to find all periods of the day to figure out whether the day is avalilble or not.

If more information or a full example is needed, please tell me.

````C#
//Month Date is a list of date from first day of month ~ end of month
foreach (var date in monthDates)
{
    var canBooking = false;

    //Assets amounts is around 20
    foreach(var asset in assets)
    {
        if (canBooking) break;

        var bookingPeriod = await this.assetOccupancyAppService.SearchBookingPeriodsAsync(
            new EasyAbp.BookingService.AssetOccupancies.Dtos.SearchBookingPeriodsInputDto()
            {
                AssetId = asset.Id,
                CurrentDateTime = currentDate,
                TargetDate = date
            });

        canBooking = bookingPeriod.Items.Any(x => x.AvailableVolume > 0);
    };
    
   UpdateCalendar(date, canBooking);
};
````

**Comment by gdlcf88** [comment]
Hi @ericeric284, Maybe generating caches in the background is a good solution.

Try these designs:
1. Create a background job named "BuildOccupancyCachesJob" to build the periods' status caches for the two months.
2. The job holds a distributed lock and begins to build the caches. Other duplicate jobs will skip if the distributed lock is busy or the cache exists.
3. Enqueue the job when the app starts, or users invoke the query API but don't match the cache.
4. Create an "AssetOccupancyChangedEventHandler". Update the cache for that asset when occupancies of an asset change.

The above cache is for the "2 months calendar" view. I think it's enough for UI.
