### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by chdphhdhz** [EasyAbp/BookingService#40]
孙云鹏，你不回复我信息了？我只好来这里跟你讲讲道理了。
你也觉得自己理亏是吧？

我都辞职了，你还要扣我最后一笔绩效。你这是在恶心人吗？

你做人还有没有底线了？ 

你拿上班时间，偷偷在这里写有报酬的开源项目。要是耽误了老板交代的进度，你就让组员拼命干活，老板一骂你，你就扣组员绩效。你是想让组员来背这个锅吗？

你要帮老板避税，说服员工把公积金折算在绩效里，行，我们信任你，但你转头就忘了，也不知道你现在记起来没有，该给的不给，你还乱扣绩效！！！

我开发出来的一个功能，一个月能给公司省三千块。你只申请到了两千块钱的一次性奖励，这也就罢了，公司还说其中一千多块已经加到了上个月的绩效里，所以我到手就七百多块钱。我怼着你要个说法，你躲不过，你说你当时刚被老板骂完，不敢给我再争取利益。你说你可以私人补给我。行吧，我相信你说的，是你能力不够，你只是蠢，不是坏。

再后来，我又发现解决一个能省代理IP的问题，每天给公司省八百块。你学聪明了，你说这次是单独奖励，不扣绩效，然后， 给500块。
你是在侮辱我吗？说还有五百做年终奖，你觉得我还愿意待到年终吗？？？

你说你管理能力不行，想让我做副手，帮你做管理，给我加500块钱。你怎么开得了这个口？在侮辱人呢？要不我每个月给你500，你帮我打点下手？

你说老板骂你了，你任务完成不了了。一个大男人，在我们面前委屈巴巴，可怜兮兮的。行吧，我们看不下去，我们帮你，天天陪你加班到好晚，结果你连加班费和调休都没谈下来，来来回回，拖了一个月，你才说实话，说你跟老板谈的是对赌，要达到老板的要求才有，有什么，要老板说了算。然后又是一副我错了，我也没办法的样子。

你是觉得你拿的钱太多了，以你的能力，不加班加点，做出勤奋的样子，不值得老板给你这么多钱是吧。但我们不是啊。

最后是我们闹到老板那里，才拿到了0.75的加班费。你作为部门经理，别的部门都在看着，不觉得打脸吗。到了评绩效的时候，你竟然还扣了那个陪你加班时间最长的兄弟的绩效，说是因为他代码写得有bug？？？帮老板补差价是吧？

为什么老板觉得你指挥不动我们？你的人心就是这样失去的，不过你肯定不在乎，反正你自己的钱已经拿够了。

这就是你招人的时候说工资绩效要三七开的原因是吧？

这样老板说技术部成本太高了的时候，你就可以把扣出来的员工绩效双手奉上，哄老板开心，免得老板骂你，扣你工资是吧？

后面公司亏钱了，你怕影响到你赚钱买房生娃，你提出来的省钱办法，就是劝组里的孕妇提前休产假？？？你怎么说得出口，你简直就是资本家的走狗，你想想你老婆也是女人啊，也要怀孕生孩子啊，她被人这样搞，你还会觉得这样没什么问题吗？甚至要人家自费买电脑替公司加班这样的话都说得出口？你还觉得自己是好人吗？

你是不是觉得自己很清高，你天天说，大家一起写这个新系统，用的新技术，能提升自己，一副 金钱皆浮云，唯有代码高 的样子。呵，你当然不在意，因为你已经拿够钱了。

你明明就是资本家的走狗，虚伪至极！能力不行就摆烂，遇到问题只会逃避，装可怜，为了保住自己的利益，侵犯别人的利益，连孕妇都欺负，真的是坏而不自知。你是活在自我欺骗中的吗？

孙云鹏，你看到这里，是不是又一脸委屈了。我现在已经不吃你这套了，你要是还是个男人，你就不要认错入流，死不悔改。你把头抬起来，好好说话，好好讲讲道理。

**Comment by gdlcf88** [comment]
😂 I am closing the issue since it's nothing to do with this module.
