### ISSUE TITLE
Should Period Add a public consurctor or factory method?

### ISSUE THREAD

**Issue by ericeric284** [EasyAbp/BookingService#8]
The entity Period has no public consuctors, which makes creating PeriodScheme hard outside the booking service moudle.

For excample if I want to create data seed for my module, I can't use PeriodSchemeManager's CreateAsync method,
because the method requires a List of Period, which I have no abiltiy to add new Period().

Currently the only way to create period is to use automapper, or use IPeriodSchemeAppService to create PeriodScheme and Periods from Dto.

**Comment by gdlcf88** [comment]
I will fix it later.

**Comment by gdlcf88** [comment]
@ericeric284 - We should keep it internal. I have added some methods in PeriodSchemeManager to help. Could you please try again?
